//Approved=false
//DriverEntry
#define fun_DriverEntry DriverEntry
//ButtonBoxEvtHandleQueryIrp
#define fun_WDFDEVICE_WDM_IRP_PREPROCESS_1 ButtonBoxEvtHandleQueryIrp
//ButtonBoxEvtDeviceAdd
#define fun_WDF_DRIVER_DEVICE_ADD ButtonBoxEvtDeviceAdd
//ButtonBoxBusEvtIoDeviceControl
#define fun_WDF_IO_QUEUE_IO_DEVICE_CONTROL ButtonBoxBusEvtIoDeviceControl
//ButtonBoxHidInternalDeviceControl
#define fun_WDF_IO_QUEUE_IO_INTERNAL_DEVICE_CONTROL ButtonBoxHidInternalDeviceControl
//ButtonBoxEvtIoStop
#define fun_WDF_IO_QUEUE_IO_STOP ButtonBoxEvtIoStop
//ButtonBoxEvtDriverContextCleanup
#define fun_WDF_OBJECT_CONTEXT_CLEANUP ButtonBoxEvtDriverContextCleanup
//SerialReadComplete
#define fun_WDF_REQUEST_COMPLETION_ROUTINE_1 SerialReadComplete
//ButtonBoxEvtReadInput
#define fun_WDF_TIMER_1 ButtonBoxEvtReadInput
